const translations = {
    id: {
        selamatDatang:
          "Selamat datang di Senergy Kos Gang Saleh, solusi cerdas untuk pengelolaan energi yang efisien dan berkelanjutan. Kami membantu penghuni kos memantau dan mengontrol penggunaan listrik secara real-time, sehingga dapat menghemat biaya dan berkontribusi pada lingkungan yang lebih baik.",
        masuk: "Masuk",
        daftar: "Daftar",
        halamanLupaPassword: "Lupa Password",
        lupaKataSandi: "Lupa kata sandi?",
        ubahKataSandi: "Ubah Kata Sandi",
        nomorTelepon: "Nomor Telepon",
        namaLengkap: "Nama Lengkap",
        email: "Email",
        kataSandi: "Kata Sandi",
        kataSandiBaru: "Kata Sandi Baru",
        konfirmasiKataSandiBaru: "Konfirmasi Kata Sandi Baru",
        belumPunyaAkun: "Belum punya akun?",
        sudahPunyaAkun: "Sudah punya akun?",
        sudahIngatKataSandi: "Sudah ingat kata sandi?",
        daftarDisini: "Daftar disini",
        masukDisini: "Masuk disini",
        placeholderEmail: "Masukkan email Anda",
        placeholderKataSandi: "Masukkan kata sandi Anda",
        placeholderNamalengkap: "Masukkan nama lengkap Anda",
        placeholderNomorTelepon: "Masukkan nomor telepon Anda",
        placeholderKataSandiBaru: "Masukkan kata sandi baru Anda",
        placeholderKonfirmasiKataSandiBaru: "Masukkan kata sandi baru Anda",
        placeholderPesan: "Masukkan pesan Anda",
        masukBerhasil: "Masuk berhasil!",
        emailGagal: "Email yang Anda masukkan salah",
        katasandiGagal: "Kata sandi yang Anda masukkan salah",
        terjadiKesalahan: "Terjadi kesalahan saat masuk",
        daftarBerhasil: "Daftar berhasil!",
        nomorTelahDigunakan: "Nomor telah digunakan",
        emailTelahDigunakan: "Email telah digunakan",
        daftarTerjadiKesalahan: "Terjadi kesalahan saat daftar",
        emailTidakDitemukan: "Email yang Anda masukkan tidak ditemukan",
        kataSandiBerhasilDiubah: "Kata sandi berhasil diubah!",
        kataSandiTidakSesuai: "Kata sandi tidak sesuai",
        kataSandiGagalDiubah: "Terjadi kesalahan saat mengubah kata sandi",
        kataSandiSamaSebelumnya: "Kata sandi telah digunakan",
        // ------Bisa digunakan di halaman Akun, Kontak, Kamar, Kontrol, dan Grafik-------
        berandaKontak: "Kontak",
        berandaBeranda: "Beranda",
        berandaAkun: "Akun",
        berandaKamar: "Kamar",
        berandaKontrol: "Kontrol",
        berandaGrafik: "Grafik",
        berandaSelamatDatang: "Selamat Datang di Senergy",
        berandaDeskripsi: "Pemantauan dan Kontrol Penggunaan Listrik di Kos Gang Saleh",
        berandaFiturUtama: "Fitur Utama",
        berandaJudulGrafik: "Grafik",
        berandaDeskripsiGrafik: "Grafik ini digunakan untuk pemantauan terhadap penggunaan energi secara real-time. Dengan fitur ini, Pengguna dapat melihat banyaknya listrik yang digunakan setiap saat, memungkinkan pengguna untuk membuat keputusan yang lebih baik dan menghindari pemborosan.",
        berandaJudulKontrol: "Kontrol",
        berandaDeskripsiKontrol: "Atur batas penggunaan listrik sesuai kebutuhan. Dengan fitur ini, Pengguna dapat menetapkan batasan penggunaan listrik untuk setiap kamar, sehingga membantu pengguna mengontrol pengeluaran dan memastikan penggunaan energi yang efisien.",
        berandaJudulNotifikasi: "Notifikasi",
        berandaDeskripsiNotifikasi: "Fitur digunakan untuk mendapatkan notifikasi langsung saat penggunaan listrik mendekati batas yang pengguna tetapkan. Fitur ini memastikan pengguna selalu mendapatkan informasi dan dapat mengambil tindakan yang diperlukan untuk menghindari pemborosan dan pengeluaran yang berlebihan.",
        berandaHakCipta: "2025 Senergy. Hak cipta dilindungi undang-undang.",
        // -------------------------------------------------------------------------------
        hasilLaporan: "Laporan Penggunaan Listrik",
        mingguan: "Mingguan",
        januariKeJuni: "Jan - Jun",
        juliKeDes: "Jul - Des",
        tabelKamar: "Kamar",
        hariIni: "Hari Ini",
        mingguIni: "Minggu Ini",
        bulanIni: "Bulan Ini",
        tagihan: "Tagihan",
        totalTagihan: "Total",
        kamar: "Kamar",
        kamar1: "Kamar 1",
        kamar2: "Kamar 2",
        kamar3: "Kamar 3",
        kamar4: "Kamar 4",
        kamar5: "Kamar 5",
        kamar6: "Kamar 6",
        kamar7: "Kamar 7",
        kamar8: "Kamar 8",
        kamar9: "Kamar 9",
        kamar10: "Kamar 10",
        kamar11: "Kamar 11",
        kamar12: "Kamar 12",
        dayGrafik: {
            Senin: "Senin",
            Selasa: "Selasa",
            Rabu: "Rabu",
            Kamis: "Kamis",
            Jumat: "Jumat",
            Sabtu: "Sabtu",
            Minggu: "Minggu"
        },
        monthGrafik: {
            Januari: "Januari",
            Februari: "Februari",
            Maret: "Maret",
            April: "April",
            Mei: "Mei",
            Juni: "Juni",
            Juli: "Juli",
            Agustus: "Agustus",
            September: "September",
            Oktober: "Oktober",
            November: "November",
            Desember: "Desember"
        },
        ubahDataUser: "Ubah",
        keluarDataUser: "Keluar",
        hapusDataUser: "Hapus Akun",
        keluarBerhasil: "Keluar berhasil!",
        dataBerhasilDiubah: "Data berhasil diubah!",
        gagalUbahData: "Gagal mengubah data",
        berhasilHapusAkun: "Hapus akun berhasil!",
        gagalHapusAkun: "Email tidak sesuai. Hapus akun gagal",
        errorHapusAkun: "Terjadi kesalahan saat hapus akun",
        hapusAkun: "Apakah Anda yakin ingin menghapus akun ini?",
        ya: "Ya",
        tidak: "Tidak",
        konfirmasiHapus: "Konfirmasi",
        batalHapus: "Batal",
        kamarKos: "Kamar",
        placeholderBatasKwh: "Masukkan batas kWh",
        placeholderSisaHari: "Masukkan sisa hari",
        hariPenggunakos: "Hari",
        labelBatasKwh: "Batas kWh",
        batasKwhKamar: "Batas",
        awalDaftarKamar: "Tanggal Daftar",
        labelSisaHari: "Sisa Hari",
        tombolOnKontrol: "Nyala",
        tombolOffKontrol: "Mati",
        labelStatusRelay: "Status",
        labelPesanAnda: "Pesan Anda",
        judulHalamanKontak: "Kontak Kami Jika Mengalami Kendala",
        pesanKirim: "Kirim",
        gunakanKamar: "Gunakan Kamar",
        kamarSedangDigunakan: "Sedang digunakan",
        tutupDaftarKamar: "Tutup",
        namaDanNomorWajibKamar: "Nama lengkap dan nomor telepon wajib diisi!",
        berhasilDaftarKamar: "Pendaftaran kamar berhasil!",
        gagalDaftarKamar: "Pendaftaran kamar gagal!",
        pilihanMcb: "Pilih MCB",
        keterangan: "Keterangan", 
        harian: "Harian",
        filterHarianStandar: "Harian Bawaan",
        filterHarianKalender: "Kalender",
        filterHarianDariTanggal: "Dari",
        filterHarianSampaiTanggal: "Sampai",
        tombolHariIni: "Hari ini",
        tombol7Hari: "7 Hari Terakhir",
        tombol30Hari: "30 Hari Terakhir",
        totalKonsumsi: "Ringkasan Total Konsumsi",
        periodePenggunaan: "Periode",
        day: "hari",
        jumlahPenggunaanPerMcb: "Total Keseluruhan",
        bulanan: "Bulanan",
        filterBulananSemua: "Semua Bulan",
        filterBulananRentang: "Rentang Bulan",
        tahun: "Tahun",
        dari: "Dari",
        sampai: "Sampai",
        keteranganFilter: "Keterangan",
        editTombolKamar: "Edit",
        berhasilEditKamar: "Data kamar berhasil diubah!",
        hapusTombolKamar: "Hapus",
        berhasilHapusKamar: "Penghuni berhasil dihapus dan kamar dikosongkan!",
        gagalHapusKamar: "Hapus kamar gagal!",
        konfirmasiHapusKamar: "Apakah Anda yakin ingin menghapus penghuni dari kamar",
        editJudul: "Edit Data Penghuni",
        editPenggunaan: "Penggunaan",
        editTombolPerbarui: "Perbarui Data",
        tombolPembatalan: "Batal",
        editInfo: "*Catatan: Pastikan data yang dimasukkan sudah benar sebelum menyimpan perubahan.",
        infoAman: "Aman",
        infoPeringatan: "Peringatan",
        infoMelebihi: "Melebihi Batas",
        catatanDaftarKamar: "*Catatan: Perhatikan kembali nama lengkap Anda dan nomor telepon Anda yang aktif."
    },
    en: {
        selamatDatang:
          "Welcome to Senergy Kos Gang Saleh, a smart solution for efficient and sustainable energy management. We help boarding house residents monitor and control electricity usage in real-time, so they can save money and contribute to a better environment.",
        masuk: "Sign In",
        daftar: "Sign Up",
        halamanLupaPassword: "Forgot Password",
        lupaKataSandi: "Forgot password?",
        ubahKataSandi: "Change Password",
        nomorTelepon: "Phone Number",
        namaLengkap: "Full Name",
        email: "Email",
        kataSandi: "Password",
        kataSandiBaru: "New Password",
        konfirmasiKataSandiBaru: "Confirm New Password",
        belumPunyaAkun: "Don't have an account yet?",
        sudahPunyaAkun: "Already have an account?",
        sudahIngatKataSandi: "Remember your password?",
        daftarDisini: "Register here",
        masukDisini: "Sign in here",                       
        placeholderEmail: "Enter your email",
        placeholderKataSandi: "Enter your password",
        placeholderNamalengkap: "Enter your full name",
        placeholderNomorTelepon: "Enter your phone number",
        placeholderKataSandiBaru: "Enter your new password",
        placeholderKonfirmasiKataSandiBaru: "Enter your new password",
        placeholderPesan: "Enter your message",
        masukBerhasil: "Login successful!",
        emailGagal: "The email you entered is incorrect",
        katasandiGagal: "The password you entered is incorrect",
        terjadiKesalahan: "An error occurred while logging in",
        daftarBerhasil: "Register successful!",
        nomorTelahDigunakan: "Number has been used",
        emailTelahDigunakan: "Email has been used",
        daftarTerjadiKesalahan: "An error occurred while registering",
        emailTidakDitemukan: "The email you entered was not found",
        kataSandiBerhasilDiubah: "Password changed successfully!",
        kataSandiTidakSesuai: "Password does not match",
        kataSandiGagalDiubah: "An error occurred while changing the password",
        kataSandiSamaSebelumnya: "Password has been used",
        // ------Bisa digunakan di halaman Akun, Kontak, Kamar, Kontrol, dan Grafik-------
        berandaKontak: "Contact",
        berandaBeranda: "Home",
        berandaAkun: "Account",
        berandaKamar: "Room",
        berandaKontrol: "Control",
        berandaGrafik: "Graph",
        berandaSelamatDatang: "Welcome to Senergy",
        berandaDeskripsi: "Monitoring and Control of Electricity Usage at Kos Gang Saleh",
        berandaFiturUtama: "Main Features",
        berandaJudulGrafik: "Graph",
        berandaDeskripsiGrafik: "This graph is used for real-time monitoring of energy usage. With this feature, Users can see how much electricity is being used at any given time, allowing users to make better decisions and avoid waste.",
        berandaJudulKontrol: "Control",
        berandaDeskripsiKontrol: "Set electricity usage limits as needed. With this feature, users can set electricity usage limits for each room, helping users control spending and ensure efficient energy use.",
        berandaJudulNotifikasi: "Notification",
        berandaDeskripsiNotifikasi: "The feature is used to get immediate notification when electricity usage approaches the limit set by the user. This feature ensures that users are always informed and can take necessary actions to avoid waste and excessive spending.",
        berandaHakCipta: "2025 Senergy. All rights reserved.",
        // -------------------------------------------------------------------------------
        hasilLaporan: "Elictricity Usage Report",
        mingguan: "Weekly",
        januariKeJuni: "Jan - Jun",
        juliKeDes: "Jul - Dec",
        tabelKamar: "Room",
        hariIni: "Today",
        mingguIni: "This Week",
        bulanIni: "This Month",
        tagihan: "Bill",
        totalTagihan: "Total",
        kamar: "Room",
        kamar1: "Room 1",
        kamar2: "Room 2",
        kamar3: "Room 3",
        kamar4: "Room 4",
        kamar5: "Room 5",
        kamar6: "Room 6",
        kamar7: "Room 7",
        kamar8: "Room 8",
        kamar9: "Room 9",
        kamar10: "Room 10",
        kamar11: "Room 11",
        kamar12: "Room 12",
        dayGrafik: {
            Senin: "Monday",
            Selasa: "Tuesday",
            Rabu: "Wednesdey",
            Kamis: "Thursday",
            Jumat: "Friday",
            Sabtu: "Saturday",
            Minggu: "Sunday"
        },
        monthGrafik: {
            Januari: "January",
            Februari: "February",
            Maret: "March",
            April: "April",
            Mei: "May",
            Juni: "June",
            Juli: "July",
            Agustus: "August",
            September: "September",
            Oktober: "October",
            November: "November",
            Desember: "December"
        },
        ubahDataUser: "Change",
        keluarDataUser: "Log Out",
        hapusDataUser: "Delete Account",
        keluarBerhasil: "Logout successful!",
        dataBerhasilDiubah: "Data successfully changed!",
        gagalUbahData: "Failed to change data",
        berhasilHapusAkun: "Delete account successful!",
        gagalHapusAkun: "Delete account failed",
        errorHapusAkun: "An error occurred while deleting the account",
        hapusAkun: "Are you sure you want to delete this account?",
        ya: "Yes",
        tidak: "No",
        konfirmasiHapus: "Confirm",
        batalHapus: "Cancel",
        kamarKos: "Room",
        placeholderBatasKwh: "Enter kWh limit",
        placeholderSisaHari: "Enter remaining day",
        hariPenggunakos: "Day",
        labelBatasKwh: "kWh Limit",
        awalDaftarKamar: "Registration Date",
        batasKwhKamar: "Limit",
        labelSisaHari: "Remaining Day",
        tombolOnKontrol: "ON",
        tombolOffKontrol: "OFF",
        labelStatusRelay: "Status",
        labelPesanAnda: "Your Message",
        judulHalamanKontak: "Contact Us If You Have Problems",
        pesanKirim: "Send",
        gunakanKamar: "Use Room",
        kamarSedangDigunakan: "In use",
        tutupDaftarKamar: "Close",
        namaDanNomorWajibKamar: "Full name and phone number are required!",
        berhasilDaftarKamar: "Room registration successful!",
        gagalDaftarKamar: "Room registration failed!",
        pilihanMcb: "Select MCB",
        keterangan: "Information", 
        harian: "Daily",
        filterHarianStandar: "Default Daily",
        filterHarianKalender: "Calendar",
        filterHarianDariTanggal: "From",
        filterHarianSampaiTanggal: "Until",
        tombolHariIni: "Today",
        tombol7Hari: "Last 7 Days",
        tombol30Hari: "Last 30 Days",
        totalKonsumsi: "Total Consumption Summary",
        periodePenggunaan: "Period",
        day: "day",
        jumlahPenggunaanPerMcb: "Total Overall",
        bulanan: "Monthly",
        filterBulananSemua: "All Months",
        filterBulananRentang: "Range of Months",
        tahun: "Year",
        dari: "From",
        sampai: "Until",
        keteranganFilter: "Description",
        editTombolKamar: "Edit",
        berhasilEditKamar: "Room data successfully changed!",
        hapusTombolKamar: "Delete",
        berhasilHapusKamar: "Occupant successfully removed and room vacated!",
        gagalHapusKamar: "Delete room failed!",
        konfirmasiHapusKamar: "Are you sure you want to remove the occupant from the room",
        editJudul: "Edit Resident Data",
        editPenggunaan: "Use",
        editTombolPerbarui: "Update Data",
        tombolPembatalan: "Cancel",
        editInfo: "*Note: Make sure the data entered is correct before saving changes.",
        infoAman: "Safe",
        infoPeringatan: "Warning",
        infoMelebihi: "Overlimit",
        catatanDaftarKamar: "*Note: Please double check your full name and your active phone number."
    }
};

export default translations;